### ISSUE TITLE
ros2 support?

### ISSUE THREAD

**Issue by hakuturu583** [osrf/vorc#15]
Hi, I am a mamber of OUXT Polaris, Japanese RobotX Team.
We are now developing our software in ROS2.
However, it seems this repo is ROS1.
Do you have plan to support ROS2?

**Comment by caguero** [comment]
Hi @hakuturu583 , not for now given the timeline. One option you could take is to use the ROS2<->ROS1 bridge. 

https://github.com/ros2/ros1_bridge
