### ISSUE TITLE
Update long/lat of marina world

### ISSUE THREAD

**Issue by mabelzhang** [osrf/vorc#23]
Creating an issue so that we don't forget.

Anyone can feel free to take this on.

Currently the long/lat are using VRX's values. Ideally we change them to the values of the new location. I believe this needs to be the point at the center of the Gazebo world, which is... somewhere.

The tasks work as they are. This is a nice-to-have in case someone adventurous checks the long lat on a real map.

**Comment by crvogt** [comment]
This sounds like something I can take care of :)

**Comment by crvogt** [comment]
Added a PR for this!

**Comment by mabelzhang** [comment]
Thanks! Usually we tag the PR in the issue, or tag the issue in the PR, and then close the issue after the PR is merged.

**Comment by crvogt** [comment]
Noted (literally)! Thank you for letting me know.

**Comment by mabelzhang** [comment]
Closing on merge of #24

**Comment by rolker** [comment]
Is it a faux-pas to comment on a closed issue? Should I open a new one?
Anyway, I guess I'm one of the adventurous types who checked against a real map and it seems like the gps is reporting a position about 400 meters south of the actual boat position.  
![vorc_project11_first_look](https://user-images.githubusercontent.com/1395479/99980447-3f84f100-2d76-11eb-836d-fd2d6d9514f8.png)

I used a map that I grabbed from Open Sea Map and I haven't verified that it is correct, so this may need further testing to confirm.

**Comment by crvogt** [comment]
@rolker 
Yes, I believe opening a new issue is best and you can reference this issue in it.

**Comment by rolker** [comment]
I'll investigate further next week and will open a new issue if I find the problem is not on my end.

**Comment by crvogt** [comment]
> I'll investigate further next week and will open a new issue if I find the problem is not on my end.

I inserted the coordinates, but only in an attempt at some realism, so the position of the boat was not meant to be exact. If you want to open up a new issue we can discuss.
