### ISSUE TITLE
Documentation: Rviz commands in sensors.md

### ISSUE THREAD

**Issue by syedjawadakhtar** [osrf/vorc#28]
When running rviz to view CoRa model, the command has to be corrected from
```
roslaunch vprc_gazebo rviz_vorc.launch
```

to

```
roslaunch vorc_gazebo rviz_vorc.launch
```
as `vprc_gazebo` isn't any package.

The other issue is that I can't find any `rviz_vorc.launch` in `vorc_gazebo` package. 

I'm only able to launch rviz and view CoRa on executing the following command: 

```
roslaunch vorc_gazebo rviz.launch
```

![Screenshot from 2020-11-01 01-55-58](https://user-images.githubusercontent.com/22319639/97789322-83f0f700-1be5-11eb-97d6-69155e9b19ab.png)

**Comment by caguero** [comment]
Thanks for reporting the issues. I have fixed the errors in https://github.com/osrf/vorc/wiki/sensors .
